### ISSUE TITLE
Attempting to use the CodeLighthouse SDK with an invalid API key creates an uncaught error

### ISSUE THREAD

**Issue by K-Mistele** [CodeLighthouse/sdk-python#2]
Attempting to use the SDK with an invalid API key creates a fatal error:
![image](https://user-images.githubusercontent.com/18430555/97088524-09c5de80-15f7-11eb-836f-277524e200c1.png)

Reasons why this shouldn't happen - if their subscription expires or they decide not to renew it or something, this will error out their application every time it runs. This would be bad. It should print out a message and then continue

**Comment by willtraweek** [comment]
Fixed on the server side -- now returns a 401 error message
